# Site settings
title: Wennder dos Santos - Software developer
description: Posts about Cordova, IONIC, ASP.NET, C#, JS, Azure and other things
# url: "http://wenndersantos.net"

# User settings
username: Wennder dos santos
user_description: Software developer
email: wennder.santos@outlook.com
twitter_username: wenndersantos
github_username:  wenndersantos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
 # - title: Series
  #  url: /series
  #- title: Tags
   # url: /tags
  #- title: About Me
   # url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
